apiVersion: 1

datasources:
  - name: lakehouse_dwh
    uid: lakehouse_dwh
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres-dwh:5432
    database: dwh
    user: dwh_user
    secureJsonData:
      password: admin1
    jsonData:
      sslmode: disable
      database: dwh
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
